import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import BackgroundSvg from "@/assets/BackgroundSvg";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movie List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={montserrat.className}>
          {children}
          <BackgroundSvg />
      </body>
    </html>
  );
}
