import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BackgroundSvg from "@/assets/BackgroundSvg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div className=" w-full absolute bottom-0 -z-10 left-0 h-[111px] flex items-end">

        <BackgroundSvg/>
        </div>
      </body>
    </html>
  );
}
